[[projects]]
title = "An improved architecture for part-based animal re-identification through semantic segmentation distillation"
description = "Add your publications here."
url = "https://openaccess.thecvf.com/content/WACV2026/html/Neto_An_improved_architecture_for_part-based_animal_re-identification_through_semantic_segmentation_WACV_2026_paper.html"
date = "2026"
tags = ["tag1", "tag2"]

[[projects]]
title = "An improved architecture for part-based animal re-identification through semantic segmentation distillation"
description = "Add your publications here."
url = "https://openaccess.thecvf.com/content/WACV2026/html/Neto_An_improved_architecture_for_part-based_animal_re-identification_through_semantic_segmentation_WACV_2026_paper.html"
date = "2026"
tags = ["tag1", "tag2"]