[[projects]]
title = "Machine learning in production"
emoji = "📚"
date = "2026 - Present"
location = "Paris, France (remote)"
description = """                                                                                                                           
To broaden my expertise beyond my core research, I am currently studying Machine Learning in production, with a focus on deploying models for efficient inference. I'll be publishing some personal projects here as I progress.

I am currently studying through the following books / materials:

- [Machine Learning in Production by Suhas Pote](https://www.amazon.fr/Machine-Learning-Production-delivering-solutions/dp/9355518102).
- [ML Systems textbook by Harvard](https://mlsysbook.ai/book/).
- [Designing Machine Learning Systems by Chip Huyen](https://www.amazon.fr/Machine-Learning-Production-delivering-solutions/dp/9355518102).
- [AI Engineer Core Track by Ed Donner](https://www.udemy.com/course/llm-engineering-master-ai-and-large-language-models/?srsltid=AfmBOopkDpR6Bh4nyXTwtGi1UNLhxXEdw6alS04cLjnBzyqRmH6jvjKg&couponCode=KEEPLEARNING).
  """
urls = []

[[projects]]
title = "Data scientist intern"
emoji = "📊"
company = "BCA Expertise"
date = "March 2023 - October 2023"
location = "Paris, France (remote)"
media = "images/projects/logo_bca.jpg"
description = """                                                                                                                           
  Integrated in the data science team of BCA Expertise, France’s biggest company in the automotive expertise sector. 
  
  - Developed a semi-supervised document classification pipeline achieving over 85% accuracy. 
  - Implemented Donut as multimodal transformer architecture combining text and image inputs. 
  - Built semi-automatic data cleaning and labeling workflow, significantly accelerating the processing of thousands of samples. 
  - Developed a vehicle mileage reading system from images using YOLO for detection and EasyOCR for text recognition.
  """
urls = []

[[projects]]
title = "Team Member of Academic Project in deep learning"
emoji = "🎓"
company = "ATOS"
date = "September 2022 - February 2023"
location = "Colombelles, France"
media = "images/projects/logo_atos.png"
description = """                                                                                                                           
  Integrated in the data science team of BCA Expertise, France’s biggest company in the automotive expertise sector. 

  - Collaboration on the development of a deep-learning pipeline for classifying fish species in underwater images.
  - Applied BiT for Fine-Grained classification, reaching over 80% accuracy.
  - Applied oversampling techniques to manage the unbalanced train dataset.
  """
urls = []

[[projects]]
title = "Research Intern in machine learning"
emoji = "🎓"
company = "LIRMM"
date = "May  2022 - August 2022"
location = "Montpellier, France"
media = "images/projects/logo_lirmm.jpeg"
description = """                                                                                                                           
Integrated in the ICAR (Image & Interaction) team of the LIRMM (Laboratory of Computer Science of Montpellier).

  - Designed and implemented an end-to-end deep learning pipeline featuring detection, tracking, feature extraction, and clustering for dog Re-ID from camera-trap images.
  - Demonstrated the feasibility of the research, directly leading to the launch of my doctoral research project.
  - Paper published at [GRETSI](https://hal-lirmm.ccsd.cnrs.fr/lirmm-04261054v1/file/GRETSI2023_BARRELET_DIAS-RIBERO-NETO_SUBSOL_LOIRE_DE-GARINE-WITTCHATITSKY_ReId_Chiens.pdf) (Francophone Conference on Signal and Image Processing) 2023.
  """


[[projects]]
title = "Java WEB Development Intern"
emoji = "🔬"
company = "Federal University of Bahia"
date = "January  2021 - August 2021"
location = "Salvador, Brazil (remote)"
media = "images/projects/logo_ufba.jpeg"
description = """                                                                                                                           
Integrated in the WEB developpement team of UFBA. UFBA is in the top-20 best universities in Brazil. 
  - Collaboration in the development of new features and maintenance of a Java-based web system responsible for managing various administrative features for the Federal University of Bahia.
  - Management of the PostgreSQL database.
  """
